name: themap

channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam

dependencies:
  - python==3.10
  - pip
  - tqdm

  # Scientific
  - numpy
  - pandas
  - matplotlib
  - seaborn

  # Misc
  - adjustText
  - h5py
  - cmake
  - watermark
  - pytz
  - pydantic

  # ML
  - scikit-learn
  - pytorch==2.4.0
  - pytorch-cuda==12.4
  - torchvision==0.19.0
  - torchaudio==2.4.0
  - fcd_torch
  - dgl<=2.0
  - dgllife
  - pytorch_geometric


  # Chemistry
  - rdkit
  - datamol
  - molfeat==0.11.0


  # Doc
  - mkdocs
  - mkdocs-material>=7.1.1
  - mkdocs-material-extensions
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-jupyter
  - markdown-include
  - mdx_truly_sane_lists
  - nbconvert
  - mike>=1.0.0

  # Dev
  - pytest>=6.0
  - pytest-dotenv
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - ruff==0.12.4
  - jupyterlab
  - nbconvert
  - ipywidgets
  - isort
  - mypy==1.17.0
  - pre-commit



  - pip:
    - chembl-webresource-client
    - dpu-utils>=0.2.13
    - biopython
    - esm
    - pot
    - pykeops
    - geomloss
    - opentsne
    - munkres
    - celluloid
    - ipycache
