name: themap

channels:
  - conda-forge
  - defaults

dependencies:
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - tqdm
  - torch
  - datamol
  - molfeat
  - dgl
  - dgllife
  - pytorch_geometric
  - pip:
    - chembl-webresource-client
    - rdkit
    - dpu-utils>=0.2.13
    - biopython
    - fair-esm
    
