name: themap

channels:
  - conda-forge
  - defaults

dependencies:
  - python == 3.10
  - pip
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - tqdm
  - pytorch >= 1.13
  - dgl
  - dgllife
  - pytorch_geometric

  # Chemistry
  - datamol
  - molfeat

  # Doc
  - mkdocs
  - mkdocs-material >=7.1.1
  - mkdocs-material-extensions
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-jupyter
  - markdown-include
  - mdx_truly_sane_lists
  - nbconvert
  - mike >=1.0.0

  # Dev
  - pytest >=6.0
  - pytest-dotenv
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - black >=22
  - ruff
  - jupyterlab
  - nbconvert  


  - pip:
    - chembl-webresource-client
    - rdkit
    - dpu-utils>=0.2.13
    - biopython
    - fair-esm
    - git+https://github.com/HFooladi/otdd
    
