name: themap

channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam/label/th23_cu118

dependencies:
  - python ==3.10
  - pip
  - tqdm

  # Scientific
  - numpy
  - pandas
  - matplotlib
  - seaborn

  # Misc
  - adjustText
  - h5py
  - cmake
  - watermark 
  - pytz
  - pydantic

  # ML
  - scikit-learn
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchtext
  - torchdata
  - dgl 
  - dgllife >=0.3.2
  - pytorch_geometric


  # Chemistry
  - rdkit
  - datamol
  - molfeat
 

  # Doc
  - mkdocs
  - mkdocs-material >=7.1.1
  - mkdocs-material-extensions
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-jupyter
  - markdown-include
  - mdx_truly_sane_lists
  - nbconvert
  - mike >=1.0.0

  # Dev
  - pytest >=6.0
  - pytest-dotenv
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - black >=22
  - ruff
  - jupyterlab
  - nbconvert 
  - ipywidgets
  - isort
  - mypy
  


  - pip:
    - chembl-webresource-client
    - dpu-utils>=0.2.13
    - biopython
    - fair-esm
    - pot
    - pykeops
    - git+https://github.com/jeanfeydy/geomloss
    - opentsne
    - munkres
    - celluloid
    - git+https://github.com/rossant/ipycache
    #- git+https://github.com/HFooladi/otdd.git --install-option="--no-deps"
    
